# Generated by Django 3.2.8 on 2021-10-27 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_customuser_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pets',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('is_birth_approximate', models.BooleanField()),
                ('birth_date', models.DateField()),
            ],
            options={
                'db_table': 'Pets',
                'managed': True,
            },
        ),
    ]
